import type { Metadata } from "next";
import { Quicksand, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  // Para fontes variáveis, usamos 'variable' ou definimos o eixo
  weight: "variable",
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={cn("font-sans", inter.variable)}>
      <body className={`${quicksand.variable} antialiased relative scroll-smooth`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
